# Generated by Django 3.2.8 on 2021-10-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopUser',
        ),
    ]
