# Generated by Django 3.2.8 on 2021-11-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20211119_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='activate_key_expires',
            new_name='activate_key_expired',
        ),
    ]
